[bibliography]
== Normative references

The following documents are referred to in the text in such a way that some or
all of their content constitutes requirements of this document. For dated
references, only the edition cited applies. For undated references, the latest
edition of the referenced document (including any amendments) applies.

* [[[onnx-part-2,ONNX 1-2]]], _Open Neural Network Exchange (ONNX) --- Part 2:
  Operator sets_

* [[[onnx-part-3,ONNX 1-3]]], _Open Neural Network Exchange (ONNX) --- Part 3:
  Conformance test package_

* [[[ieee754,IEEE 754-2019]]], _IEEE Standard for Floating-Point Arithmetic_

* [[[iso9899,ISO/IEC 9899]]], _Information technology --- Programming languages
  --- C_

* [[[iso10646,ISO/IEC 10646]]], _Information technology --- Universal Coded
  Character Set (UCS)_

* [[[rfc8259,IETF RFC 8259]]], _The JavaScript Object Notation (JSON) Data
  Interchange Format_

* [[[rfc2119,IETF RFC 2119]]], _Key words for use in RFCs to Indicate
  Requirement Levels_

NOTE: Protocol Buffers is deliberately not a normative reference. It has no
citable specification with a stable identifier, and this document therefore
states the binary encoding itself, in <<serialization>>, rather than citing
one. An implementation may still be built on a Protocol Buffers library; see
<<protobuf-relationship>>.
