[bibliography]
== Normative references

The following documents are referred to in the text in such a way that some or
all of their content constitutes requirements of this document. For dated
references, only the edition cited applies. For undated references, the latest
edition of the referenced document (including any amendments) applies.

* [[[onnx-part-2,ONNX 1-2]]], _Open Neural Network Exchange (ONNX) --- Part 2:
  Operator sets_

* [[[onnx-part-3,ONNX 1-3]]], _Open Neural Network Exchange (ONNX) --- Part 3:
  Conformance test package_

* [[[ieee754,IEEE 754-2019]]], _IEEE Standard for Floating-Point Arithmetic_

* [[[iso9899,ISO/IEC 9899]]], _Information technology --- Programming languages
  --- C_

* [[[iso10646,ISO/IEC 10646]]], _Information technology --- Universal Coded
  Character Set (UCS)_

* [[[rfc8259,IETF RFC 8259]]], _The JavaScript Object Notation (JSON) Data
  Interchange Format_

* [[[rfc2119,IETF RFC 2119]]], _Key words for use in RFCs to Indicate
  Requirement Levels_

NOTE: Editorial. Protocol Buffers has no citable normative reference with a
stable identifier. Either (a) normatively include the required subset of the
wire format in an annex, or (b) cite a dated release. This is to be resolved
before the committee draft; see also the editorial note in <<serialization>>.
A bibliography clause admits no editorial note block, so this appears as a
note.
